### ISSUE TITLE
Fix python "json" types

### ISSUE THREAD

**Issue by kjrokos** [vmware/vmware-aria-operations-integration-sdk#102]
### Is your feature request related to a problem? Please describe.

In a number of places, we're using Dict[str, Any] for the type of python "json". It turns out that has some limitations in mypy, and we should switch to Dict[str, object], which will type-check better (e.g., we shouldn't need to disable or ignore type checking when working with these types).

### Describe the solution you'd like

Switch `Dict[str, Any]` to `Dict[str, object]`, which will type-check better.

### Additional context

See discussion [here](https://stackoverflow.com/questions/51291722/define-a-jsonable-type-using-mypy-pep-526) for more details and alternatives.

**Comment by MarkArbogast** [comment]
After further investigation, we'll change on case-by-case basis.
