### ISSUE TITLE
mp-build should prompt for a container registry when the container registry is an empty string in config.json

### ISSUE THREAD

**Issue by quirogas** [vmware/vmware-aria-operations-integration-sdk#114]
### Describe the bug

When running mp-build, the container registry field can't be left blank. However, a user can manually edit the `config.json` file and leave an empty string, which causes mp-build to log into the Docker hub and then fail.

![image](https://user-images.githubusercontent.com/22756465/233171686-7ac9afbd-fcf6-43d6-985d-03487ee77264.png)

### Reproduction steps

1. edit the `config.json` file. Enter an empty string for `docker_registry` key value. 
```
{
...
 "docker_registry": "",

}
```
2. run `mp-build`

### Expected behavior

We should prompt the user to enter a registry.

**Comment by MarkArbogast** [comment]
Idea: don't write config.json until we've verified that the registry is valid
