### ISSUE TITLE
Documentation: References > Python SDK Library Class/Method documentation

### ISSUE THREAD

**Issue by MarkArbogast** [vmware/vmware-aria-operations-integration-sdk#147]
Ensure all Python Library documentation is complete and up to date.

These are known issues that need to be completed:
- Describe how keys work in attribute.py
- Describe all event parameters in event.py

Generate documentation from source files for inclusion in main documentation

**Comment by kjrokos** [comment]
Python library documentation is automatically generated by GitHub and published to GitHub Pages documentation site.
