### ISSUE TITLE
Documentation: Separate Site

### ISSUE THREAD

**Issue by MarkArbogast** [vmware/vmware-aria-operations-integration-sdk#151]
Consider hosting documentation on a dedicated server. Examples:

https://engineering-expectations.ara.decc.vmware.com/docs/

https://tanzu.vmware.com/developer/

https://github.com/vmware-tanzu/tanzu-dev-portal

See this for a potential server (what engineering-expectations uses):

https://gohugo.io/

**Comment by kjrokos** [comment]
Site is now live in a beta state. We are using `mkdocs`
