### ISSUE TITLE
Sample Management Pack: vCenter MP extension

### ISSUE THREAD

**Issue by MarkArbogast** [vmware/vmware-aria-operations-integration-sdk#165]
Create an easily extensible sample of adding metrics to the vCenter MP
1. VM Disk Consolidation status
2. Network stack / gateway properties

- [x] Add to samples
- [x] Add README explaining how to use (focus on build to start, with pointers to our other README guides if they want to extend/edit)
    - [x] Add links to pre-reqs
    - [x] Add instructions for mp-build
    - [x] Add screenshot (and/or nice text description) showing what the sample does by default
 - [x] Add SSL
 - [x] Ensure host system uniqueness across VCenter environments

**Comment by kjrokos** [comment]
SSL Support is present, but we are disabling certificate verification for now. 

We spent some time trying to get it to work, but were unable to force the SSL Context to recognize a custom root certificate, which we would need for verification of a self-signed certificate.
