### ISSUE TITLE
Add support for SVG icons in mp-init

### ISSUE THREAD

**Issue by MarkArbogast** [vmware/vmware-aria-operations-integration-sdk#174]
VMware Aria Operations supports both PNG and SVG icons. Integration SDK `mp-init` script only supports PNG today.

**Comment by kjrokos** [comment]
I added SVG support to mp-init, and it doesn't seem to work in Aria Ops - it may be only AdapterKind/ResourceKind/TraversalSpec icons that support SVG - if that is the case, no change is necessary as those icons are not currently validated.


![Image](https://github.com/vmware/vmware-aria-operations-integration-sdk/assets/3310870/69f21b88-bcd2-4229-8e1a-759427aa2f49)
