### ISSUE TITLE
Tag validation

### ISSUE THREAD

**Issue by quirogas** [vmware/vmware-aria-operations-integration-sdk#200]
### Is your feature request related to a problem? Please describe.

When a user enters an invalid tag format during `mp-build` setup, `mp-build` will try to use the tag, which will cause it to fail. The tool correctly handles the error; however, the message displayed comes from docker and is unclear.

```
17:00:19,405 vmware_aria_operations_integration_sdk.mp_build ERROR Unable to build pak file
17:00:19,407 vmware_aria_operations_integration_sdk.mp_build ERROR ERROR: Unable to build Docker file at /Users/user_name/management-pack:
 {'message': 'invalid reference format'}
```

### Describe the solution you'd like

If we could validate that the tag has a valid format, we could prevent the user from running into this case.

**Comment by kjrokos** [comment]
See also #114
