### ISSUE TITLE
mp-build Advanced setting requirement

### ISSUE THREAD

**Issue by quirogas** [vmware/vmware-aria-operations-integration-sdk#201]
### Describe the bug

When using the SDK tools, if the user's Docker docker socket is not enabled by default, the tools assume Docker is not running.

### Reproduction steps

Disable default Docker socket in advance settings:

![image](https://github.com/vmware/vmware-aria-operations-integration-sdk/assets/22756465/ce47869b-e256-44fe-a241-f42f0ca7aaa5)

### Expected behavior

If Docker is running but can't detect the socket, the tools should be more explicit about the cause of the error (Unable to connect to the Docker daemon socket). This should also be mentioned in the requirements section.

**Comment by MarkArbogast** [comment]
We need to do 2 things:
1. Document this requirement
2. Update code to prompt user to check this setting on error
