### ISSUE TITLE
Add Millicores to the list of Units

### ISSUE THREAD

**Issue by quirogas** [vmware/vmware-aria-operations-integration-sdk#80]
### Is your feature request related to a problem? Please describe.

I cannot add MILLICORES as a UNIT in a metric description for the describe.xml.

### Describe the solution you'd like

Add MILLICORES to the Units module for the python SDK.

**Comment by kjrokos** [comment]
Resolved in [0186112](https://github.com/vmware/vmware-aria-operations-integration-sdk/commit/018611210b08fec2e937d3db6384c4f87932cb35)
